### ISSUE TITLE
App should work offline

### ISSUE THREAD

**Issue by rcmenno** [rodekruis/relief-app#5]
### **User Story**
As a user
I want to be able to do the relief process offline
So that I don't have to fall back to primitive methods nor be blocked during my work

### **What needs to be done**
- [ ] the whole app / flow needs to work online with an exception for installing it and sending the aggregated data

### ***Implementation***
ReliefBox will be ported on a screen by screen basis to a progressive web app in which service workers make sure the app can work fully offline once installed.

Since at first, all data will live offline, the login flow will not be implemented as long as it's not needed yet.

Screens to port (might change depending on what's encountered):
- [x] choose_input_method
- [ ] delete_distrib_confirm
- [ ] duplicate_error
- [ ] entry_not_found
- [ ] entry
- [x] index_distrib
- [ ] index
- [ ] input_video
- [ ] input
- [ ] list_distrib_delete
- [ ] list_distrib
- [ ] ~login~
- [ ] name_distrib
- [ ] no_data
- [ ] no_distrib
- [ ] profile
- [ ] ~signup~
- [x] ~test_login~
- [x] upload_data
- [x] upload_error
- [x] view_data

**Comment by w3eydi** [comment]
Is there any progress regarding this issue?

**Comment by rcmenno** [comment]
It's done. Merging it now.
